name: Update badges

on:
  workflow_dispatch:
    inputs:
      CREDLY_USER:
        default: "ronnieutd"
  schedule:
    # Runs at 0am UTC every Sunday
    - cron: "0 0 * * 0"
jobs:
  update-readme:
    name: Update Readme badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
