name: Update README badges

on:
  workflow_dispatch:
  schedule:
    # Runs at 0am UTC every Sunday
    - cron: "0 0 * * 0"
jobs:
  update-readme:
    name: Update README badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: ronnieutd
          CREDLY_SORT: POPULAR
